export const data = [
    {
        id: 0,
        title: "Blabla",
        description: "asdasfasdasdasd",
        img: "img01.jpg",
        price: 45.0,
        status: "wie neu",
        brand: "Grocery Tarm Fields",
        shipping: true,
        quantity: 1,
        category: "Möbel",
        rating: 4,
    },
    {
        id: 1,
        title: "Blabla",
        description: "asdasfasdasdasd",
        img: "img01.jpg",
        price: 45.0,
        status: "wie neu",
        brand: "Grocery Tarm Fields",
        shipping: true,
        quantity: 1,
        category: "Möbel",
        rating: 4,
    },
    {
        id: 2,
        title: "Blabla",
        description: "asdasfasdasdasd",
        img: "img01.jpg",
        price: 45.0,
        status: "wie neu",
        brand: "Grocery Tarm Fields",
        shipping: true,
        quantity: 1,
        category: "Möbel",
        rating: 4,
    },
    {
        id: 3,
        title: "Blabla",
        description: "asdasfasdasdasd",
        img: "img01.jpg",
        price: 45.0,
        status: "wie neu",
        brand: "Grocery Tarm Fields",
        shipping: true,
        quantity: 1,
        category: "Möbel",
        rating: 4,
    },
];
