export const data =[
    {
        id: 0,
        title: "Stuhl",
        description: "Kleine Produktbeschreibung",
        img: "stuhl.png",
        price: 45.00,
        status: "wie neu",
        brand: "Grocery Tarm Fields",
        shipping: true,
        quantity: 320,
        category: "Möbel",
        rating: 4,
    },
    {
        id: 1,
        title: "Grüner Sofa",
        description: "Kleine Produktbeschreibung",
        img: "couch.png",
        price: 45.00,
        status: "wie neu",
        brand: "Grocery Tarm Fields",
        shipping: true,
        quantity: 1,
        category: "Möbel",
        rating: 4,
    },
    {
        id: 2,
        title: "Weißer Schuh",
        description: "Kleine Produktbeschreibung",
        img: "schuh.png",
        price: 45.00,
        status: "wie neu",
        brand: "Grocery Tarm Fields",
        shipping: true,
        quantity: 1,
        category: "Möbel",
        rating: 4,
    },
    {
        id: 3,
        title: "Blabla",
        description: "asdasfasdasdasd",
        img: "buch.png",
        price: 45.00,
        status: "wie neu",
        brand: "Grocery Tarm Fields",
        shipping: true,
        quantity: 1,
        category: "Möbel",
        rating: 4,
    },
    {
        id: 4,
        title: "Stuhl",
        description: "Kleine Produktbeschreibung",
        img: "smartphone.png",
        price: 45.00,
        status: "wie neu",
        brand: "Grocery Tarm Fields",
        shipping: true,
        quantity: 320,
        category: "Möbel",
        rating: 4,
    },
    {
        id: 5,
        title: "Stuhl",
        description: "Kleine Produktbeschreibung",
        img: "camera.png",
        price: 45.00,
        status: "wie neu",
        brand: "Grocery Tarm Fields",
        shipping: true,
        quantity: 320,
        category: "Möbel",
        rating: 4,
    },
    {
        id: 6,
        title: "Stuhl",
        description: "Kleine Produktbeschreibung",
        img: "tablet.png",
        price: 45.00,
        status: "wie neu",
        brand: "Grocery Tarm Fields",
        shipping: true,
        quantity: 320,
        category: "Möbel",
        rating: 4,
    },
    {
        id: 7,
        title: "Stuhl",
        description: "Kleine Produktbeschreibung",
        img: "playstation.png",
        price: 45.00,
        status: "wie neu",
        brand: "Grocery Tarm Fields",
        shipping: true,
        quantity: 320,
        category: "Möbel",
        rating: 4,
    },
]




